function CreateOM_Script_class
FunctionList=OMFunctionList;
ClassString=['classdef OM_Script <handle',newline,...
    'properties (Hidden=false)',newline,...
    'OMScript=[];',newline,...
    'end',newline,...
    AddMethods(FunctionList),newline,...
    'end'];
fileID = fopen(['OM_Script.m'],'w');
fprintf(fileID, '%s',ClassString);
fclose('all');
end
function MethodString=AddMethods(FunctionList)
MethodString=['methods'];
for i=1:length(FunctionList)
    MethodString=[MethodString,newline,AddFunction(FunctionList{i})];
end
MethodString=[MethodString,newline,...
    'function [result,str]=Launch(obj,start)',newline...
    '[~,path]=system([''ECHO '',''%OPENMODELICAHOME%bin'']);path=path(1:end-1);addpath(path);',newline,...
    'ScriptID=fopen([path,''\TEMPscript.mos''],''w'');',newline,...
    'fprintf(ScriptID,''%s\n'',obj.OMScript);',newline,...
    'fclose(''all'');',newline,...
    'cd OMResults;',newline,...
    'if string(start)=="DoNotWait"',newline,...
    '[result,str]=system([''start '',path,''\omc '',[path,''\TEMPscript.mos'']]);',newline,...
    'elseif string(start)=="Wait"',newline,...
    '[result,str]=system([path,''\omc '',[path,''\TEMPscript.mos'']]);',newline,...
    'end',newline,...
    'cd .. ;',newline,...
    'end',newline,...
    'function obj=getComponents(obj,ArgString)',newline,...
    'obj.OMScript=[obj.OMScript,''','getComponents','('',ArgString,'');'',newline];',newline...
    'end',newline,...
    'end'];
end
function FunctionString=AddFunction(FunctionName)
FunctionString=['function obj=',FunctionName,'(obj,ArgString)',newline,...
    'obj.OMScript=[obj.OMScript,''',FunctionName,'('',ArgString,'');'',newline];',newline...
    'end'];
end
%-------------------------------------------
function FunctionList=OMFunctionList
FunctionList=[];
ScriptString='getClassNames(OpenModelica.Scripting)';
[~,ResponseString]=SendScriptToOM(ScriptString);
ResponseString=char(regexp(ResponseString,['(?<=\{).*(?=\})'],'match'));
ClassList=regexp(ResponseString,',','split');

ScriptString='getPackages(OpenModelica.Scripting)';
[~,ResponseString]=SendScriptToOM(ScriptString);
ResponseString=char(regexp(ResponseString,['(?<=\{).*(?=\})'],'match'));
PackageList=regexp(ResponseString,',','split');

for i=1:length(ClassList)
    if 0==any(strcmp(ClassList{i},PackageList))
        FunctionList{end+1}=ClassList{i};
    end
end

end
